#ifndef DGTOTP_H
#define DGTOTP_H

#include <map>
#include <memory>
#include <string>
#include <vector>

#include "Member.h"
#include "Parameter.h"
#include "RA.h"
#include "Verifier.h"

/**
 * DGTOTP facade - wraps the protocol building blocks behind a stable API.
 *
 * This class does not re-implement the algorithms. It orchestrates the
 * existing RA / Member / Verifier / Parameter classes and exposes the
 * eight syntax algorithms described in the paper.
 */
class DGTOTP
{
public:
    /**
     * Password tuple produced by the DGTOTP protocol
     */
    struct Password
    {
        /// TOTP password component
        std::string totp_password;

        /// Chameleon hash collision randomness
        std::string collision_randomness;

        /// Encrypted member identity
        std::string identity_ciphertext;

        /// Convert structured password to a legacy vector representation
        /// @return Password vector
        std::vector<std::string> toVector() const;

        /// Build structured password from a legacy vector representation
        /// @param[in] password Password vector
        /// @return Structured password tuple
        static Password fromVector(const std::vector<std::string> &password);
    };

    /**
     * Join receipt exchanged between the server-side RA and the client-side
     * member process in the TLS demo.
     */
    struct JoinReceipt
    {
        /// Shared member key ks
        std::vector<unsigned char> shared_key;

        /// Member alpha index serialized as 4 bytes
        std::vector<unsigned char> alpha_bytes;
    };

    /**
     * Cached member-side materials managed by the facade
     */
    struct MemberMaterials
    {
        /// Member protocol instance
        Member member;

        /// Join receipt cached for subsequent PwGen calls
        std::vector<unsigned char *> join_receipt;

        /// Whether Join has completed for this member
        bool joined = false;

        /// Destructor
        ~MemberMaterials();

        /// Release cached Join receipt
        void resetJoinReceipt();
    };

    /// Constructor
    DGTOTP();

    /// Destructor
    ~DGTOTP();

    DGTOTP(const DGTOTP &) = delete;
    DGTOTP &operator=(const DGTOTP &) = delete;

    /// Paper syntax: RASetup
    /// @param[in] security_parameter         Security parameter
    /// @param[in] group_name                 Group instance identifier
    /// @param[in] group_member_count         Number of group members
    /// @param[in] start_time                 Start time (timestamp)
    /// @param[in] end_time                   End time (timestamp)
    /// @param[in] verification_period        Verification period (delta_e)
    /// @param[in] password_generation_period Password generation period (delta_s)
    void RASetup(int security_parameter, const std::string &group_name, int group_member_count,
                 long start_time, long end_time, int verification_period,
                 int password_generation_period);

    /// Import shared public parameters without initializing server-side RA state
    /// @param[in] security_parameter         Security parameter
    /// @param[in] group_name                 Group instance identifier
    /// @param[in] group_member_count         Number of group members
    /// @param[in] start_time                 Start time (timestamp)
    /// @param[in] end_time                   End time (timestamp)
    /// @param[in] verification_period        Verification period (delta_e)
    /// @param[in] password_generation_period Password generation period (delta_s)
    void ImportParameters(int security_parameter, const std::string &group_name, int group_member_count,
                          long start_time, long end_time, int verification_period,
                          int password_generation_period);

    /// Paper syntax: PInit
    /// @param[in] member_id Member identifier
    void PInit(const std::string &member_id);

    /// Paper syntax: Join
    /// @param[in] member_id Member identifier
    /// @param[in] time      Current time
    void Join(const std::string &member_id, long time);

    /// Join and export the receipt for cross-process demos
    /// @param[in] member_id Member identifier
    /// @param[in] time      Current time
    /// @return Join receipt containing ks and alpha
    JoinReceipt JoinAndExportReceipt(const std::string &member_id, long time);

    /// Import a join receipt previously generated by JoinAndExportReceipt
    /// @param[in] member_id Member identifier
    /// @param[in] receipt   Serialized join receipt
    void ImportJoinReceipt(const std::string &member_id, const JoinReceipt &receipt);

    /// Paper syntax: GetSD
    /// @param[in] member_id Member identifier
    /// @param[in] time      Current time
    /// @return Secret seed as a hexadecimal string
    std::string GetSD(const std::string &member_id, long time);

    /// Paper syntax: PwGen
    /// @param[in] member_id Member identifier
    /// @param[in] time      Current time
    /// @return Generated DGTOTP password tuple
    Password PwGen(const std::string &member_id, long time);

    /// Paper syntax: Verify
    /// @param[in] password Password tuple
    /// @param[in] time     Current time
    /// @return Verification result (1 success, 0 failure)
    int Verify(const Password &password, long time);

    /// Paper syntax: Revoke
    /// @param[in] member_id Member identifier
    /// @return 1 if successful, 0 if member not found
    int Revoke(const std::string &member_id);

    /// Paper syntax: Open
    /// @param[in] password Password tuple
    /// @param[in] time     Current time
    /// @return Member ID if successful, empty string otherwise
    std::string Open(const Password &password, long time);

    /// Get shared protocol parameters
    /// @return Parameter instance
    const Parameter &getParameter() const;

    /// Get registration authority instance
    /// @return Registration authority instance
    const RA &getRA() const;

private:
    /// Get cached materials for a member
    /// @param[in] member_id Member identifier
    /// @return Cached member materials
    MemberMaterials &requireMaterials(const std::string &member_id);

    /// Ensure RASetup has been called
    void ensureSetup() const;

    /// Refresh published verifier-side state
    /// @param[in] time Current time
    void refreshPublishedState(long time);

    /// Clear cached state and release owned resources
    void clearState();

    /// Shared protocol parameters
    Parameter params;

    /// Registration authority instance
    RA ra;

    /// Verifier instance
    Verifier verifier;

    /// Mapping from member ID to member-side cached materials
    std::map<std::string, std::unique_ptr<MemberMaterials>> memberIdToMaterialsMap;

    /// Whether the facade has completed RASetup
    bool isSetup = false;

    /// Whether this facade instance owns initialized RA-side state
    bool hasRAState = false;
};

#endif // DGTOTP_H
